name: Java CI with Maven
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '16'
      - name: Build with Maven
        run: mvn clean package
      - name: Archive artifacts (API)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: EasyDatapack API
          path: api/target/EasyDatapack-API.jar
      - name: Archive artifacts (backend)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: EasyDatapack
          path: backend/target/EasyDatapack.jar
      - name: Deploy JavaDocs
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.0.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 16
          target-folder: javadoc